# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f602601a9106945d37db05705b3e5fa1b3d2b2cb18a5cc9905a56b3b349cfa3da46100df81485e50900c38e96ba895c7de9655646c449b35f8770dfa18f22d9

test:
  secret_key_base: e05e8a3692ee155609d0e4134f190a415b00b7aeb32f3b14694f578a697af9f6406679b6091c011fcafcf0939ffd77a148da80b5bfe76f24839b8ec111661425

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
